### ISSUE TITLE
add readme file

### ISSUE THREAD

**Issue by B-Dmitriy** [github-profile-achievements/russian#37]

**Comment by gomzyakov** [comment]
Что вы имеете ввиду, @B-Dmitriy?

Файл [README.md](https://github.com/github-profile-achievements/russian/blob/main/README.md) присутствует в корне проекта. Он, одновременно, является и README-файлом для репозитория и MD-файлом для генерации https://github-profile-achievements.github.io/russian/

**Comment by gomzyakov** [comment]
@B-Dmitriy 

Закрываю issue
