### ISSUE TITLE
Отметить значёк "Discussion answered" как недостижимый

### ISSUE THREAD

**Issue by gomzyakov** [github-profile-achievements/russian#45]
Можно сделать по аналогии с https://github.com/github-profile-achievements/english

**Comment by 1murs** [comment]
Да

**Comment by gomzyakov** [comment]
@1murs 

Не хотите сделать PR по аналогии с https://github.com/github-profile-achievements/english ? ;)

<img width="873" alt="image" src="https://github.com/github-profile-achievements/russian/assets/1460709/3f10f090-c1d7-4d49-975d-7a38c96d7941">

**Comment by anonexistent** [comment]
спасибо!

**Comment by gomzyakov** [comment]
Правки внесены, всем спасибо!
