### ISSUE TITLE
Уберите лишнее

### ISSUE THREAD

**Issue by alekseysafronov** [github-profile-achievements/russian#47]
Вы всйо добавляете добавляете всякие фичи / большая часть из которых вообще нафиг не нужна / и этог всйо значительно усложняет жизнь другим людям / не думали никогда чтобы не добавлять фичи, а делать уборку ненужных штук вместо этого???

**Comment by gomzyakov** [comment]
@alekseysafronov 

О каких конкретно "лишних фичах" вы говорите, Алексей?

**Comment by alekseysafronov** [comment]
Обо всех лишних штуках говорить не возьмусь. Все таки их тоже не глупые люди делали. Спасибо и хвала им за это. Но взять хотя бы интерфейс этих комментариев. Есть тут неиспользуемые элементы ну или совсем ненужные, которые усложняют использование по назначению и увеличивают время использования. 
![Screenshot at Nov 29 18-22-27](https://github.com/github-profile-achievements/russian/assets/1806162/7ae8ef47-82f4-4baf-a599-d62523cfe551)

Зачастую мне приходится самому редактировать код страницы и скрывать лишние элементы или целые блоки, чтобы мое использование сайта было быстрым по его прямому назначению. Из списка "отредактированных" у меня википедия и стэковерфлоу например. Еще для примера, когда мне нужно разобраться с новой технологией например - я скрываю лишнее с глаз долой, чтобы была концентрация и все лишнее не мешало и не замыливало глаза. И это проблема глобальная. И почему то людям пофиг и они любят все усложнять, думая что простое не ценится и никто покупать это не будет...

**Comment by alekseysafronov** [comment]
Я походу вообще не туда написал)))
