### ISSUE TITLE
Обновить градацию достижений

### ISSUE THREAD

**Issue by azya0** [github-profile-achievements/russian#51]
Никогда не видел градацию достижений, как указано в файле. 
Вместо этого у пользователей (например [Alexander Gomzyakov](https://github.com/gomzyakov)), градация достижений выглядит как:
![image](https://github.com/user-attachments/assets/b7d6e013-8b2f-4695-bb7b-51d5315573d8)

**Comment by azya0** [comment]
Стоит отметить, что GitHub **не использует отдельные иконки** для новых достижений. <br>
Они создают ```<span/>```, в классах которого указывают параметр ```achievement-tier-label--...``` <br>
где вместо многоточия могут стоять: ```bronze```, ```silver```, ```gold```.

**Comment by gomzyakov** [comment]
@azya0 Привет!

Что значит "обновить градацию достижений"? Какие-то из достижений, на ваш взгляд, неактуальны или недостижимы?
